Warning: test1(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.
Warning: test2(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.
Warning: test1(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.
Warning: test2(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.
Warning: test1(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.
Warning: test2(): Attempt to echo a string that might be tainted in %s006.php on line %d
tainted string.