Warning: test1(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.
Warning: test2(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.
Warning: test1(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.
Warning: test2(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.
Warning: test1(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.
Warning: test2(): Attempt to echo a string that might be csased in %s006.php on line %d
csased string.